apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      name: pod2
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - image: 123399119691.dkr.ecr.us-east-1.amazonaws.com/shoe
        name: frontend
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080

